using System;
using System.Collections.Generic;
using System.Text;

namespace Kidoo.Learn.Enums
{
    public enum District
    {
        Abroad = 1,
        Dhaka = 2,
        Faridpur = 5,
        Gazipur = 3,
        Gopalganj = 4,
        Jamalpur = 66,
        Kishoreganj = 6,
        Madaripur = 7,
        Manikganj = 8,
        Munshiganj = 9,
        Mymensingh = 10,
        Narayanganj = 11,
        Narsingdi = 12,
        Netrakona = 13,
        Rajbari = 14,
        Shariatpur = 15,
        Sherpur = 16,
        Tangail = 17,
        Bogra = 18,
        Joypurhat = 19,
        Naogaon = 20,
        Natore = 21,
        Nawabganj = 22,
        Pabna = 23,
        Rajshahi = 24,
        Sirajganj = 25,
        Dinajpur = 26,
        Gaibandha = 27,
        Kurigram = 28,
        Lalmonirhat = 29,
        Nilphamari = 30,
        Panchagarh = 31,
        Rangpur = 32,
        Thakurgaon = 33,
        Barguna = 34,
        Barisal = 35,
        Bhola = 36,
        Jhalokati = 37,
        Patuakhali = 38,
        Pirojpur = 39,
        Bandarban = 40,
        Brahmanbaria = 41,
        Chandpur = 42,
        Chittagong = 43,
        Comilla = 44,
        Coxsbazar = 45,
        Feni = 46,
        Khagrachari = 47,
        Lakshmipur = 48,
        Noakhali = 49,
        Rangamati = 50,
        Habiganj = 51,
        Moulvibazar = 52,
        Sunamganj = 53,
        Sylhet = 54,
        Bagerhat = 55,
        Chuadanga = 56,
        Jessore = 57,
        Jhenaidah = 58,
        Khulna = 60,
        Kushtia = 61,
        Magura = 62,
        Meherpur = 63,
        Narail = 64,
        Satkhira = 65
    }
}
